# R1

In [34]:
import pandas as pd

url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2026-02.parquet"

df = pd.read_parquet(url)

print(df.shape)
print(df.head())

(3399866, 20)
   VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0         7  2026-02-01 00:05:57   2026-02-01 00:05:57              1.0
1         7  2026-02-01 00:35:58   2026-02-01 00:35:58              1.0
2         2  2026-02-01 00:08:41   2026-02-01 00:39:32              1.0
3         1  2026-02-01 00:29:06   2026-02-01 00:41:04              0.0
4         1  2026-02-01 00:53:52   2026-02-01 01:11:21              0.0

   trip_distance  RatecodeID store_and_fwd_flag  PULocationID  DOLocationID  \
0           0.94         1.0                  N           107           170
1           1.93         1.0                  N           234           141
2           9.99         1.0                  N           138            68
3           1.70         1.0                  N           209            13
4           3.70         1.0                  N           249           229

   payment_type  fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0             1          7.2   0.00      0.5        0.00           0.0
1             1         11.4   0.00      0.5        3.43           0.0
2             1         44.3   6.00      0.5       11.01           0.0
3             1         12.8   4.25      0.5        3.70           0.0
4             1         19.8   4.25      0.5        6.35           0.0

   improvement_surcharge  total_amount  congestion_surcharge  Airport_fee  \
0                    1.0         12.95                   2.5         0.00
1                    1.0         20.58                   2.5         0.00
2                    1.0         67.81                   2.5         1.75
3                    1.0         22.25                   2.5         0.00
4                    1.0         31.90                   2.5         0.00

   cbd_congestion_fee
0                0.75
1                0.75
2                0.75
3                0.75
4                0.75

In [35]:
print("\nMissing Percentage:")
print((df.isnull().mean()*100).sort_values(ascending=False))

print("\nUnique Values:")
print(df.nunique().sort_values(ascending=False))

Missing Percentage:
passenger_count          30.098745
congestion_surcharge     30.098745
store_and_fwd_flag       30.098745
RatecodeID               30.098745
Airport_fee              30.098745
tpep_dropoff_datetime     0.000000
VendorID                  0.000000
tpep_pickup_datetime      0.000000
DOLocationID              0.000000
payment_type              0.000000
trip_distance             0.000000
PULocationID              0.000000
extra                     0.000000
fare_amount               0.000000
mta_tax                   0.000000
tip_amount                0.000000
improvement_surcharge     0.000000
tolls_amount              0.000000
total_amount              0.000000
cbd_congestion_fee        0.000000
dtype: float64

Unique Values:
tpep_pickup_datetime     1587963
tpep_dropoff_datetime    1587241
total_amount               19930
fare_amount                12616
trip_distance               4719
tip_amount                  4210
tolls_amount                1169
DOLocationID                 261
PULocationID                 259
extra                         41
mta_tax                       10
passenger_count                9
Airport_fee                    8
RatecodeID                     7
payment_type                   5
VendorID                       4
congestion_surcharge           4
improvement_surcharge          4
cbd_congestion_fee             3
store_and_fwd_flag             2
dtype: int64

# R2

In [36]:
import pandas as pd
import numpy as np

audit = []

for col in df.columns:

    row = {}

    row["column"] = col
    row["dtype"] = str(df[col].dtype)
    row["% missing"] = round(df[col].isnull().mean()*100, 2)
    row["distinct"] = df[col].nunique()

    # Min / Max
    if pd.api.types.is_numeric_dtype(df[col]):
        row["min/max"] = f"{df[col].min()} / {df[col].max()}"

        # Outlier Evidence using IQR
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        outliers = ((df[col] < lower) | (df[col] > upper)).sum()

        row["outliers"] = outliers

        if outliers > 0:
            row["proposed treatment"] = "Keep + RobustScaler / Log Transform"
        else:
            row["proposed treatment"] = "No action required"

    else:
        row["min/max"] = str(df[col].value_counts().head(3).to_dict())
        row["outliers"] = "N/A"

        if row["distinct"] <= 10:
            row["proposed treatment"] = "One-Hot Encoding"
        else:
            row["proposed treatment"] = "Group Rare + One-Hot Encoding"

    audit.append(row)

audit_df = pd.DataFrame(audit)

audit_df

,column,dtype,% missing,distinct,min/max,outliers,proposed treatment
0,VendorID,int32,0.0,4,1 / 7,683449,Keep + RobustScaler / Log Transform
1,tpep_pickup_datetime,datetime64[us],0.0,1587963,"{Timestamp('2026-02-07 22:48:00'): 14, Timesta...",N/A,Group Rare + One-Hot Encoding
2,tpep_dropoff_datetime,datetime64[us],0.0,1587241,"{Timestamp('2026-02-26 19:00:08'): 14, Timesta...",N/A,Group Rare + One-Hot Encoding
3,passenger_count,float64,30.1,9,0.0 / 9.0,401854,Keep + RobustScaler / Log Transform
4,trip_distance,float64,0.0,4719,0.0 / 328522.2,380461,Keep + RobustScaler / Log Transform
5,RatecodeID,float64,30.1,7,1.0 / 99.0,213909,Keep + RobustScaler / Log Transform
6,store_and_fwd_flag,object,30.1,2,"{'N': 2374445, 'Y': 2104}",N/A,One-Hot Encoding
7,PULocationID,int32,0.0,259,1 / 265,0,No action required
8,DOLocationID,int32,0.0,261,1 / 265,0,No action required
9,payment_type,int64,0.0,5,0 / 4,51272,Keep + RobustScaler / Log Transform
10,fare_amount,float64,0.0,12616,-2084.1 / 2084.1,212446,Keep + RobustScaler / Log Transform
11,extra,float64,0.0,41,-7.5 / 20.71,438461,Keep + RobustScaler / Log Transform
12,mta_tax,float64,0.0,10,-0.5 / 4.75,65508,Keep + RobustScaler / Log Transform
13,tip_amount,float64,0.0,4210,-68.0 / 500.0,179939,Keep + RobustScaler / Log Transform
14,tolls_amount,float64,0.0,1169,-111.79 / 111.79,212681,Keep + RobustScaler / Log Transform
15,improvement_surcharge,float64,0.0,4,-1.0 / 1.0,134369,Keep + RobustScaler / Log Transform
16,total_amount,float64,0.0,19930,-2088.85 / 2088.85,284764,Keep + RobustScaler / Log Transform
17,congestion_surcharge,float64,30.1,4,-2.5 / 2.5,289979,Keep + RobustScaler / Log Transform
18,Airport_fee,float64,30.1,8,-1.75 / 26.75,201301,Keep + RobustScaler / Log Transform
19,cbd_congestion_fee,float64,0.0,3,-0.75 / 0.75,0,No action required

# R3

In [37]:
missing_cols = [
    "passenger_count",
    "RatecodeID",
    "store_and_fwd_flag",
    "congestion_surcharge",
    "Airport_fee"
]

In [38]:
for col in missing_cols:
    print("\n" + "="*60)
    print("COLUMN:", col)

    temp = df.copy()
    temp[col + "_missing"] = temp[col].isna()

    print(
        temp.groupby(col + "_missing")["trip_distance"]
        .mean()
    )

    print(
        temp.groupby(col + "_missing")["fare_amount"]
        .mean()
    )

    print(
        temp.groupby(col + "_missing")["total_amount"]
        .mean()
    )

============================================================
COLUMN: passenger_count
passenger_count_missing
False     3.346450
True     12.966495
Name: trip_distance, dtype: float64
passenger_count_missing
False    19.243154
True     27.228753
Name: fare_amount, dtype: float64
passenger_count_missing
False    28.576176
True     33.682954
Name: total_amount, dtype: float64

============================================================
COLUMN: RatecodeID
RatecodeID_missing
False     3.346450
True     12.966495
Name: trip_distance, dtype: float64
RatecodeID_missing
False    19.243154
True     27.228753
Name: fare_amount, dtype: float64
RatecodeID_missing
False    28.576176
True     33.682954
Name: total_amount, dtype: float64

============================================================
COLUMN: store_and_fwd_flag
store_and_fwd_flag_missing
False     3.346450
True     12.966495
Name: trip_distance, dtype: float64
store_and_fwd_flag_missing
False    19.243154
True     27.228753
Name: fare_amount, dtype: float64
store_and_fwd_flag_missing
False    28.576176
True     33.682954
Name: total_amount, dtype: float64

============================================================
COLUMN: congestion_surcharge
congestion_surcharge_missing
False     3.346450
True     12.966495
Name: trip_distance, dtype: float64
congestion_surcharge_missing
False    19.243154
True     27.228753
Name: fare_amount, dtype: float64
congestion_surcharge_missing
False    28.576176
True     33.682954
Name: total_amount, dtype: float64

============================================================
COLUMN: Airport_fee
Airport_fee_missing
False     3.346450
True     12.966495
Name: trip_distance, dtype: float64
Airport_fee_missing
False    19.243154
True     27.228753
Name: fare_amount, dtype: float64
Airport_fee_missing
False    28.576176
True     33.682954
Name: total_amount, dtype: float64

In [39]:

missing_cols = [
    "passenger_count",
    "RatecodeID",
    "store_and_fwd_flag",
    "congestion_surcharge",
    "Airport_fee"
]

# Create missing indicators
for col in missing_cols:
    df[col + "_missing"] = df[col].isna().astype(int)


temp_df = df.copy()


num_cols = [
    "passenger_count",
    "congestion_surcharge",
    "Airport_fee"
]


cat_cols = [
    "RatecodeID",
    "store_and_fwd_flag"
]

print("NUMERIC COLUMNS")

for col in num_cols:

    before_mean = df[col].mean()
    before_median = df[col].median()
    before_std = df[col].std()

    # Median Imputation tempariraly
    temp_df[col] = temp_df[col].fillna(temp_df[col].median())

    after_mean = temp_df[col].mean()
    after_median = temp_df[col].median()
    after_std = temp_df[col].std()

    print(f"\nColumn: {col}")

    print("Before Imputation")
    print("Mean   :", round(before_mean, 4))
    print("Median :", round(before_median, 4))
    print("Std    :", round(before_std, 4))

    print("\nAfter Imputation")
    print("Mean   :", round(after_mean, 4))
    print("Median :", round(after_median, 4))
    print("Std    :", round(after_std, 4))

print("CATEGORICAL COLUMNS")

for col in cat_cols:
    before_missing = df[col].isna().sum()
    temp_df[col] = temp_df[col].fillna(
        temp_df[col].mode()[0]
    )

    after_missing = temp_df[col].isna().sum()

    print(f"\nColumn: {col}")
    print("Missing Before:", before_missing)
    print("Missing After :", after_missing)
    print("Imputation Used: Mode")

NUMERIC COLUMNS

Column: passenger_count
Before Imputation
Mean   : 1.2299
Median : 1.0
Std    : 0.6347

After Imputation
Mean   : 1.1607
Median : 1.0
Std    : 0.5411

Column: congestion_surcharge
Before Imputation
Mean   : 2.1726
Median : 2.5
Std    : 0.9073

After Imputation
Mean   : 2.2711
Median : 2.5
Std    : 0.7733

Column: Airport_fee
Before Imputation
Mean   : 0.143
Median : 0.0
Std    : 0.5204

After Imputation
Mean   : 0.1
Median : 0.0
Std    : 0.44
CATEGORICAL COLUMNS

Column: RatecodeID
Missing Before: 1023317
Missing After : 0
Imputation Used: Mode

Column: store_and_fwd_flag
Missing Before: 1023317
Missing After : 0
Imputation Used: Mode

# R4

In [40]:
numeric_cols = df.select_dtypes(include=['int64','int32','float64']).columns

skew_table = pd.DataFrame({
    "column": numeric_cols,
    "skewness": [df[col].skew() for col in numeric_cols]
})

skew_table.sort_values("skewness", ascending=False)

                          column    skewness
2                  trip_distance  267.401897
10                    tip_amount    5.805544
11                  tolls_amount    5.353912
15                   Airport_fee    5.053492
0                       VendorID    4.537289
3                     RatecodeID    4.534159
1                passenger_count    3.372040
7                    fare_amount    3.204593
13                  total_amount    2.916229
8                          extra    1.908797
6                   payment_type    1.171473
21           Airport_fee_missing    0.867749
20  congestion_surcharge_missing    0.867749
17       passenger_count_missing    0.867749
19    store_and_fwd_flag_missing    0.867749
18            RatecodeID_missing    0.867749
4                   PULocationID   -0.258505
5                   DOLocationID   -0.304058
16            cbd_congestion_fee   -1.002638
14          congestion_surcharge   -2.733649
12         improvement_surcharge   -5.769417
9                        mta_tax   -8.104855

In [41]:
for col in numeric_cols:
    print("\n", col)
    print(df[col].describe(percentiles=[0.01,0.05,0.25,0.5,0.75,0.95,0.99]))

 VendorID
count    3.399866e+06
mean     1.878228e+00
std      7.035353e-01
min      1.000000e+00
1%       1.000000e+00
5%       1.000000e+00
25%      2.000000e+00
50%      2.000000e+00
75%      2.000000e+00
95%      2.000000e+00
99%      7.000000e+00
max      7.000000e+00
Name: VendorID, dtype: float64

 passenger_count
count    2.376549e+06
mean     1.229941e+00
std      6.347402e-01
min      0.000000e+00
1%       1.000000e+00
5%       1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
95%      2.000000e+00
99%      4.000000e+00
max      9.000000e+00
Name: passenger_count, dtype: float64

 trip_distance
count    3.399866e+06
mean     6.241963e+00
std      6.336499e+02
min      0.000000e+00
1%       0.000000e+00
5%       2.200000e-01
25%      1.000000e+00
50%      1.800000e+00
75%      3.680000e+00
95%      1.205000e+01
99%      1.941000e+01
max      3.285222e+05
Name: trip_distance, dtype: float64

 RatecodeID
count    2.376549e+06
mean     5.250941e+00
std      1.974612e+01
min      1.000000e+00
1%       1.000000e+00
5%       1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
95%      5.000000e+00
99%      9.900000e+01
max      9.900000e+01
Name: RatecodeID, dtype: float64

 PULocationID
count    3.399866e+06
mean     1.611912e+02
std      6.713427e+01
min      1.000000e+00
1%       1.300000e+01
5%       4.500000e+01
25%      1.140000e+02
50%      1.610000e+02
75%      2.330000e+02
95%      2.490000e+02
99%      2.630000e+02
max      2.650000e+02
Name: PULocationID, dtype: float64

 DOLocationID
count    3.399866e+06
mean     1.608020e+02
std      7.107263e+01
min      1.000000e+00
1%       7.000000e+00
5%       4.200000e+01
25%      1.070000e+02
50%      1.610000e+02
75%      2.340000e+02
95%      2.560000e+02
99%      2.630000e+02
max      2.650000e+02
Name: DOLocationID, dtype: float64

 payment_type
count    3.399866e+06
mean     8.210903e-01
std      6.833522e-01
min      0.000000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      1.000000e+00
75%      1.000000e+00
95%      2.000000e+00
99%      4.000000e+00
max      4.000000e+00
Name: payment_type, dtype: float64

 fare_amount
count    3.399866e+06
mean     2.164672e+01
std      1.856912e+01
min     -2.084100e+03
1%       3.000000e+00
5%       5.800000e+00
25%      1.000000e+01
50%      1.630000e+01
75%      2.750000e+01
95%      5.830000e+01
99%      8.070000e+01
max      2.084100e+03
Name: fare_amount, dtype: float64

 extra
count    3.399866e+06
mean     1.013819e+00
std      1.697290e+00
min     -7.500000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      1.000000e+00
95%      5.000000e+00
99%      6.000000e+00
max      2.071000e+01
Name: extra, dtype: float64

 mta_tax
count    3.399866e+06
mean     4.865765e-01
std      1.017811e-01
min     -5.000000e-01
1%       0.000000e+00
5%       5.000000e-01
25%      5.000000e-01
50%      5.000000e-01
75%      5.000000e-01
95%      5.000000e-01
99%      5.000000e-01
max      4.750000e+00
Name: mta_tax, dtype: float64

 tip_amount
count    3.399866e+06
mean     2.639165e+00
std      3.834607e+00
min     -6.800000e+01
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      2.000000e+00
75%      3.790000e+00
95%      1.000000e+01
99%      1.721000e+01
max      5.000000e+02
Name: tip_amount, dtype: float64

 tolls_amount
count    3.399866e+06
mean     4.907929e-01
std      2.101911e+00
min     -1.117900e+02
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
95%      7.460000e+00
99%      7.460000e+00
max      1.117900e+02
Name: tolls_amount, dtype: float64

 improvement_surcharge
count    3.399866e+06
mean     9.530165e-01
std      2.456413e-01
min     -1.000000e+00
1%       0.000000e+00
5%       1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
95%      1.000000e+00
99%      1.000000e+00
max      1.000000e+00
Name: improvement_surcharge, dtype: float64

 total_amount
count    3.399866e+06
mean     3.011325e+01
std      2.207985e+01
min     -2.088850e+03
1%       7.000000e+00
5%       1.195000e+01
25%      1.764000e+01
50%      2.400000e+01
75%      3.543000e+01
95%      7.476000e+01
99%      1.046500e+02
max      2.088850e+03
Name: total_amount, dtype: float64

 congestion_surcharge
count    2.376549e+06
mean     2.172574e+00
std      9.073471e-01
min     -2.500000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      2.500000e+00
50%      2.500000e+00
75%      2.500000e+00
95%      2.500000e+00
99%      2.500000e+00
max      2.500000e+00
Name: congestion_surcharge, dtype: float64

 Airport_fee
count    2.376549e+06
mean     1.430396e-01
std      5.203535e-01
min     -1.750000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
95%      1.750000e+00
99%      1.750000e+00
max      2.675000e+01
Name: Airport_fee, dtype: float64

 cbd_congestion_fee
count    3.399866e+06
mean     5.224810e-01
std      3.530696e-01
min     -7.500000e-01
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      7.500000e-01
75%      7.500000e-01
95%      7.500000e-01
99%      7.500000e-01
max      7.500000e-01
Name: cbd_congestion_fee, dtype: float64

 passenger_count_missing
count    3.399866e+06
mean     3.009875e-01
std      4.586873e-01
min      0.000000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      1.000000e+00
95%      1.000000e+00
99%      1.000000e+00
max      1.000000e+00
Name: passenger_count_missing, dtype: float64

 RatecodeID_missing
count    3.399866e+06
mean     3.009875e-01
std      4.586873e-01
min      0.000000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      1.000000e+00
95%      1.000000e+00
99%      1.000000e+00
max      1.000000e+00
Name: RatecodeID_missing, dtype: float64

 store_and_fwd_flag_missing
count    3.399866e+06
mean     3.009875e-01
std      4.586873e-01
min      0.000000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      1.000000e+00
95%      1.000000e+00
99%      1.000000e+00
max      1.000000e+00
Name: store_and_fwd_flag_missing, dtype: float64

 congestion_surcharge_missing
count    3.399866e+06
mean     3.009875e-01
std      4.586873e-01
min      0.000000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      1.000000e+00
95%      1.000000e+00
99%      1.000000e+00
max      1.000000e+00
Name: congestion_surcharge_missing, dtype: float64

 Airport_fee_missing
count    3.399866e+06
mean     3.009875e-01
std      4.586873e-01
min      0.000000e+00
1%       0.000000e+00
5%       0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      1.000000e+00
95%      1.000000e+00
99%      1.000000e+00
max      1.000000e+00
Name: Airport_fee_missing, dtype: float64

# R5

In [42]:
print("R5 - ENCODING AUDIT")

categorical_cols = [
    "VendorID",
    "payment_type",
    "RatecodeID",
    "store_and_fwd_flag",
    "PULocationID",
    "DOLocationID"
]

for col in categorical_cols:
    unique_count = df[col].nunique(dropna=True)

    print(f"\nColumn: {col}")
    print(f"Unique Categories: {unique_count}")

    if unique_count <= 10:
        print("Encoding Choice: One-Hot Encoding")
        print("Reason: Low-cardinality categorical feature.")
    else:
        print("Encoding Choice: Group Rare Categories + One-Hot Encoding")
        print("Reason: High-cardinality categorical feature.")

R5 - ENCODING AUDIT

Column: VendorID
Unique Categories: 4
Encoding Choice: One-Hot Encoding
Reason: Low-cardinality categorical feature.

Column: payment_type
Unique Categories: 5
Encoding Choice: One-Hot Encoding
Reason: Low-cardinality categorical feature.

Column: RatecodeID
Unique Categories: 7
Encoding Choice: One-Hot Encoding
Reason: Low-cardinality categorical feature.

Column: store_and_fwd_flag
Unique Categories: 2
Encoding Choice: One-Hot Encoding
Reason: Low-cardinality categorical feature.

Column: PULocationID
Unique Categories: 259
Encoding Choice: Group Rare Categories + One-Hot Encoding
Reason: High-cardinality categorical feature.

Column: DOLocationID
Unique Categories: 261
Encoding Choice: Group Rare Categories + One-Hot Encoding
Reason: High-cardinality categorical feature.

In [43]:
! touch pipeline.py

In [44]:
%%writefile pipeline.py

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, RobustScaler
from sklearn.linear_model import LinearRegression


def build_pipeline():

    numeric_cols = [
        "trip_distance",
        "fare_amount",
        "tip_amount",
        "tolls_amount",
        "extra",
        "Airport_fee",
        "congestion_surcharge",
        "cbd_congestion_fee"
    ]

    categorical_cols = [
        "VendorID",
        "payment_type",
        "RatecodeID",
        "store_and_fwd_flag",
        "PULocationID",
        "DOLocationID"
    ]

    num_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", RobustScaler())
    ])

    cat_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer([
        ("num", num_pipeline, numeric_cols),
        ("cat", cat_pipeline, categorical_cols)
    ])

    model_pipeline = Pipeline([
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ])

    return model_pipeline

Overwriting pipeline.py

# R6

In [45]:
from pipeline import build_pipeline

model_pipeline = build_pipeline()

print(model_pipeline)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['trip_distance',
                                                   'fare_amount', 'tip_amount',
                                                   'tolls_amount', 'extra',
                                                   'Airport_fee',
                                                   'congestion_surcharge',
                                                   'cbd_congestion_fee']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['VendorID', 'payment_type',
                                                   'RatecodeID',
                                                   'store_and_fwd_flag',
                                                   'PULocationID',
                                                   'DOLocationID'])])),
                ('model', LinearRegression())])